export const BASE_URL = process.env.PUBLIC_URL
// export const API_URL = 'https://btlbd.xyz/bpa-api/'
export const API_URL = 'http://localhost:8000/'

export const ACTION_STATUS = 'ACTION_STATUS'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_ERROR = 'SET_ERROR'
export const SET_HOME_DATA = 'SET_HOME_DATA'
export const ADD_TO_CART = 'ADD_TO_CART'
export const SET_VALIDATION = 'SET_VALIDATION'
export const SET_USER = 'SET_USER'
export const DISCOUNT_TAG = 'DC1000'
export const SET_ROOM_RESULT = 'SET_ROOM_RESULT'
export const SET_ROOM_IN_CART = 'SET_ROOM_IN_CART'
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'


// Action status 
export const LOGIN_ACTION_STATUS = 'LOGIN_ACTION_STATUS'
export const FORGOT_PASS_STATUS = 'FORGOT_PASS_STATUS'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const PROFILE_EDIT_STATUS = 'PROFILE_EDIT_STATUS'
export const EDIT_PROFILE_PHOTO = 'EDIT_PROFILE_PHOTO'
export const PASS_UPDATE_STATUS = 'PASS_UPDATE_STATUS'
export const EMP_ADD_STATUS = 'EMP_ADD_STATUS'
export const DEPARTMENT_ADD_STATUS = 'DEPARTMENT_ADD_STATUS'
export const LEAVE_MAN_STATUS = 'LEAVE_MAN_STATUS'
export const MEETING_ROOM_BOOK = 'MEETING_ROOM_BOOK'
export const CONVEYANCE_STATUS = 'CONVEYANCE_STATUS'
export const PROJECT_STATUS = 'PROJECT_STATUS'
export const MESSAGE_STATUS = 'MESSAGE_STATUS'
